name: hide_n_seek
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  navigation_builder: ^0.0.4
  validators: ^3.0.0
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  steganograph: ^1.0.0
  image_picker: ^1.1.1
  share_plus: ^9.0.0
  image: ^3.3.0
  path_provider: ^2.1.3
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
